# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\agb\Documents\workspace\gmail api\mail_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(661, 520)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 661, 21))
        self.menubar.setObjectName("menubar")
        self.menuAction = QtWidgets.QMenu(self.menubar)
        self.menuAction.setObjectName("menuAction")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionRead_mail = QtWidgets.QAction(MainWindow)
        self.actionRead_mail.setObjectName("actionRead_mail")
        self.actionSend_mail = QtWidgets.QAction(MainWindow)
        self.actionSend_mail.setObjectName("actionSend_mail")
        self.menuAction.addAction(self.actionRead_mail)
        self.menuAction.addAction(self.actionSend_mail)
        self.menubar.addAction(self.menuAction.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuAction.setTitle(_translate("MainWindow", "Action"))
        self.actionRead_mail.setText(_translate("MainWindow", "Read mail tab"))
        self.actionRead_mail.setStatusTip(_translate("MainWindow", "New mail tab reader"))
        self.actionRead_mail.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionSend_mail.setText(_translate("MainWindow", "Send mail tab"))
        self.actionSend_mail.setStatusTip(_translate("MainWindow", "Send mail tab"))
        self.actionSend_mail.setShortcut(_translate("MainWindow", "Ctrl+N"))
