# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\agb\Documents\workspace\gmail api\tab_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pprint import pp

class Ui_Form(object):
    
    mail_list = []
    content = []
    mail_subject = []
    
    def setupUi(self, Form, tab_name):

        
        
        Form.setObjectName("Form")
        
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setMaximumSize(QtCore.QSize(780, 400))
        self.tabWidget.setStyleSheet("background-color: rgb(255, 255, 255);\n""")
        self.tabWidget.setObjectName("tabWidget")
        self.tabWidget.setTabsClosable(True)
        self.tab = QtWidgets.QWidget()
        self.tab.setEnabled(True)
        self.tab.setObjectName("tab")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 40, 23))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 40, 111, 261))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.listWidget = QtWidgets.QListWidget(self.gridLayoutWidget_3)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_5.addWidget(self.listWidget, 0, 0, 1, 1)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(139, 40, 381, 261))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.gridLayoutWidget_4)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout_6.addWidget(self.plainTextEdit, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, tab_name)
        
        
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(80, 0, 31, 31))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.refresh_button = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        
        
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/refresh_icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refresh_button.setIcon(icon)
        self.refresh_button.setObjectName("refresh_button")
        self.gridLayout_2.addWidget(self.refresh_button, 0, 0, 1, 1)
        
        
        
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(200, 10, 309, 20))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setReadOnly(True)
        self.verticalLayout.addWidget(self.lineEdit)

        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(140, 10, 51, 21))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Mail list:"))
        self.label_2.setText(_translate("Form", "Subject:"))


    def closeUI(self, action):
        self.tabWidget.tabCloseRequested.connect(action)
        
        
    def add_mail_list(self):
        
        self.listWidget.addItems(self.mail_list)
    
    def refreshUI(self, action):
        self.refresh_button.clicked.connect(action)
        
    def list_event(self):
        self.listWidget.currentRowChanged.connect(self.mail_content)
    
    def mail_content(self):
        idx = self.listWidget.currentRow()
        self.plainTextEdit.clear()
        self.lineEdit.clear()
        self.plainTextEdit.appendHtml(self.content[idx])
        self.lineEdit.insert(self.mail_subject[idx])
        
    def clear_all(self):
        self.mail_list = []
        self.content = []
        self.mail_subject = []
    
    